export interface CurrencyInfo {
  code: string
  name: string
  symbol: string
  symbolNative: string
  decimalDigits: number
  rounding: number
  flag: string
}

export const ISO_CURRENCIES: CurrencyInfo[] = [
  { code: 'AED', name: 'UAE Dirham', symbol: 'AED', symbolNative: 'د.إ', decimalDigits: 2, rounding: 0, flag: '🇦🇪' },
  { code: 'AFN', name: 'Afghan Afghani', symbol: 'AFN', symbolNative: '؋', decimalDigits: 2, rounding: 0, flag: '🇦🇫' },
  { code: 'ALL', name: 'Albanian Lek', symbol: 'ALL', symbolNative: 'L', decimalDigits: 2, rounding: 0, flag: '🇦🇱' },
  { code: 'AMD', name: 'Armenian Dram', symbol: 'AMD', symbolNative: '֏', decimalDigits: 2, rounding: 0, flag: '🇦🇲' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ANG', symbolNative: 'ƒ', decimalDigits: 2, rounding: 0, flag: '🇧🇶' },
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'AOA', symbolNative: 'Kz', decimalDigits: 2, rounding: 0, flag: '🇦🇴' },
  { code: 'ARS', name: 'Argentine Peso', symbol: 'ARS', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇦🇷' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇦🇺' },
  { code: 'AWG', name: 'Aruban Florin', symbol: 'AWG', symbolNative: 'ƒ', decimalDigits: 2, rounding: 0, flag: '🇦🇼' },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: 'AZN', symbolNative: '₼', decimalDigits: 2, rounding: 0, flag: '🇦🇿' },
  { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'BAM', symbolNative: 'КМ', decimalDigits: 2, rounding: 0, flag: '🇧🇦' },
  { code: 'BBD', name: 'Barbadian Dollar', symbol: 'BBD', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇧🇧' },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: 'BDT', symbolNative: '৳', decimalDigits: 2, rounding: 0, flag: '🇧🇩' },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'BGN', symbolNative: 'лв', decimalDigits: 2, rounding: 0, flag: '🇧🇬' },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: 'BHD', symbolNative: 'د.ب', decimalDigits: 3, rounding: 0, flag: '🇧🇭' },
  { code: 'BIF', name: 'Burundian Franc', symbol: 'BIF', symbolNative: 'FBu', decimalDigits: 0, rounding: 0, flag: '🇧🇮' },
  { code: 'BMD', name: 'Bermudan Dollar', symbol: 'BMD', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇧🇲' },
  { code: 'BND', name: 'Brunei Dollar', symbol: 'BND', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇧🇳' },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'BOB', symbolNative: 'Bs.', decimalDigits: 2, rounding: 0, flag: '🇧🇴' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', symbolNative: 'R$', decimalDigits: 2, rounding: 0, flag: '🇧🇷' },
  { code: 'BSD', name: 'Bahamian Dollar', symbol: 'BSD', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇧🇸' },
  { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'BTN', symbolNative: 'Nu.', decimalDigits: 2, rounding: 0, flag: '🇧🇹' },
  { code: 'BWP', name: 'Botswanan Pula', symbol: 'BWP', symbolNative: 'P', decimalDigits: 2, rounding: 0, flag: '🇧🇼' },
  { code: 'BYN', name: 'Belarusian Ruble', symbol: 'BYN', symbolNative: 'Br', decimalDigits: 2, rounding: 0, flag: '🇧🇾' },
  { code: 'BZD', name: 'Belize Dollar', symbol: 'BZD', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇧🇿' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇨🇦' },
  { code: 'CDF', name: 'Congolese Franc', symbol: 'CDF', symbolNative: 'FC', decimalDigits: 2, rounding: 0, flag: '🇨🇩' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', symbolNative: '₣', decimalDigits: 2, rounding: 0, flag: '🇨🇭' },
  { code: 'CLP', name: 'Chilean Peso', symbol: 'CLP', symbolNative: '$', decimalDigits: 0, rounding: 0, flag: '🇨🇱' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: 'CN¥', symbolNative: '¥', decimalDigits: 2, rounding: 0, flag: '🇨🇳' },
  { code: 'COP', name: 'Colombian Peso', symbol: 'COP', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇨🇴' },
  { code: 'CRC', name: 'Costa Rican Colón', symbol: 'CRC', symbolNative: '₡', decimalDigits: 2, rounding: 0, flag: '🇨🇷' },
  { code: 'CUP', name: 'Cuban Peso', symbol: 'CUP', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇨🇺' },
  { code: 'CVE', name: 'Cape Verdean Escudo', symbol: 'CVE', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇨🇻' },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'CZK', symbolNative: 'Kč', decimalDigits: 2, rounding: 0, flag: '🇨🇿' },
  { code: 'DJF', name: 'Djiboutian Franc', symbol: 'DJF', symbolNative: 'Fdj', decimalDigits: 0, rounding: 0, flag: '🇩🇯' },
  { code: 'DKK', name: 'Danish Krone', symbol: 'DKK', symbolNative: 'kr', decimalDigits: 2, rounding: 0, flag: '🇩🇰' },
  { code: 'DOP', name: 'Dominican Peso', symbol: 'DOP', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇩🇴' },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'DZD', symbolNative: 'د.ج', decimalDigits: 2, rounding: 0, flag: '🇩🇿' },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'EGP', symbolNative: 'ج.م', decimalDigits: 2, rounding: 0, flag: '🇪🇬' },
  { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'ERN', symbolNative: 'Nfk', decimalDigits: 2, rounding: 0, flag: '🇪🇷' },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'ETB', symbolNative: 'Br', decimalDigits: 2, rounding: 0, flag: '🇪🇹' },
  { code: 'EUR', name: 'Euro', symbol: '€', symbolNative: '€', decimalDigits: 2, rounding: 0, flag: '🇪🇺' },
  { code: 'FJD', name: 'Fijian Dollar', symbol: 'FJD', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇫🇯' },
  { code: 'FKP', name: 'Falkland Islands Pound', symbol: 'FKP', symbolNative: '£', decimalDigits: 2, rounding: 0, flag: '🇫🇰' },
  { code: 'GBP', name: 'British Pound', symbol: '£', symbolNative: '£', decimalDigits: 2, rounding: 0, flag: '🇬🇧' },
  { code: 'GEL', name: 'Georgian Lari', symbol: 'GEL', symbolNative: '₾', decimalDigits: 2, rounding: 0, flag: '🇬🇪' },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: 'GHS', symbolNative: '₵', decimalDigits: 2, rounding: 0, flag: '🇬🇭' },
  { code: 'GIP', name: 'Gibraltar Pound', symbol: 'GIP', symbolNative: '£', decimalDigits: 2, rounding: 0, flag: '🇬🇮' },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'GMD', symbolNative: 'D', decimalDigits: 2, rounding: 0, flag: '🇬🇲' },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'GNF', symbolNative: 'FG', decimalDigits: 0, rounding: 0, flag: '🇬🇳' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'GTQ', symbolNative: 'Q', decimalDigits: 2, rounding: 0, flag: '🇬🇹' },
  { code: 'GYD', name: 'Guyanaese Dollar', symbol: 'GYD', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇬🇾' },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇭🇰' },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'HNL', symbolNative: 'L', decimalDigits: 2, rounding: 0, flag: '🇭🇳' },
  { code: 'HRK', name: 'Croatian Kuna', symbol: 'HRK', symbolNative: 'kn', decimalDigits: 2, rounding: 0, flag: '🇭🇷' },
  { code: 'HTG', name: 'Haitian Gourde', symbol: 'HTG', symbolNative: 'G', decimalDigits: 2, rounding: 0, flag: '🇭🇹' },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'HUF', symbolNative: 'Ft', decimalDigits: 0, rounding: 0, flag: '🇭🇺' },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'IDR', symbolNative: 'Rp', decimalDigits: 0, rounding: 0, flag: '🇮🇩' },
  { code: 'ILS', name: 'Israeli New Shekel', symbol: '₪', symbolNative: '₪', decimalDigits: 2, rounding: 0, flag: '🇮🇱' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', symbolNative: '₹', decimalDigits: 2, rounding: 0, flag: '🇮🇳' },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'IQD', symbolNative: 'د.ع', decimalDigits: 3, rounding: 0, flag: '🇮🇶' },
  { code: 'IRR', name: 'Iranian Rial', symbol: 'IRR', symbolNative: '﷼', decimalDigits: 0, rounding: 0, flag: '🇮🇷' },
  { code: 'ISK', name: 'Icelandic Króna', symbol: 'ISK', symbolNative: 'kr', decimalDigits: 0, rounding: 0, flag: '🇮🇸' },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: 'JMD', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇯🇲' },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'JOD', symbolNative: 'د.ا', decimalDigits: 3, rounding: 0, flag: '🇯🇴' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', symbolNative: '¥', decimalDigits: 0, rounding: 0, flag: '🇯🇵' },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KES', symbolNative: 'KSh', decimalDigits: 2, rounding: 0, flag: '🇰🇪' },
  { code: 'KGS', name: 'Kyrgyzstani Som', symbol: 'KGS', symbolNative: 'сом', decimalDigits: 2, rounding: 0, flag: '🇰🇬' },
  { code: 'KHR', name: 'Cambodian Riel', symbol: 'KHR', symbolNative: '៛', decimalDigits: 2, rounding: 0, flag: '🇰🇭' },
  { code: 'KMF', name: 'Comorian Franc', symbol: 'KMF', symbolNative: 'FC', decimalDigits: 0, rounding: 0, flag: '🇰🇲' },
  { code: 'KPW', name: 'North Korean Won', symbol: 'KPW', symbolNative: '₩', decimalDigits: 0, rounding: 0, flag: '🇰🇵' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', symbolNative: '₩', decimalDigits: 0, rounding: 0, flag: '🇰🇷' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'KWD', symbolNative: 'د.ك', decimalDigits: 3, rounding: 0, flag: '🇰🇼' },
  { code: 'KYD', name: 'Cayman Islands Dollar', symbol: 'KYD', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇰🇾' },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: 'KZT', symbolNative: '₸', decimalDigits: 2, rounding: 0, flag: '🇰🇿' },
  { code: 'LAK', name: 'Laotian Kip', symbol: 'LAK', symbolNative: '₭', decimalDigits: 0, rounding: 0, flag: '🇱🇦' },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'LBP', symbolNative: 'ل.ل', decimalDigits: 0, rounding: 0, flag: '🇱🇧' },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'LKR', symbolNative: 'Rs', decimalDigits: 2, rounding: 0, flag: '🇱🇰' },
  { code: 'LRD', name: 'Liberian Dollar', symbol: 'LRD', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇱🇷' },
  { code: 'LSL', name: 'Lesotho Loti', symbol: 'LSL', symbolNative: 'L', decimalDigits: 2, rounding: 0, flag: '🇱🇸' },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'LYD', symbolNative: 'د.ل', decimalDigits: 3, rounding: 0, flag: '🇱🇾' },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'MAD', symbolNative: 'د.م.', decimalDigits: 2, rounding: 0, flag: '🇲🇦' },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'MDL', symbolNative: 'L', decimalDigits: 2, rounding: 0, flag: '🇲🇩' },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'MGA', symbolNative: 'Ar', decimalDigits: 0, rounding: 0, flag: '🇲🇬' },
  { code: 'MKD', name: 'Macedonian Denar', symbol: 'MKD', symbolNative: 'ден', decimalDigits: 2, rounding: 0, flag: '🇲🇰' },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'MMK', symbolNative: 'K', decimalDigits: 0, rounding: 0, flag: '🇲🇲' },
  { code: 'MNT', name: 'Mongolian Tugrik', symbol: 'MNT', symbolNative: '₮', decimalDigits: 0, rounding: 0, flag: '🇲🇳' },
  { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP', symbolNative: 'MOP$', decimalDigits: 2, rounding: 0, flag: '🇲🇴' },
  { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'MRU', symbolNative: 'UM', decimalDigits: 2, rounding: 0, flag: '🇲🇷' },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: 'MUR', symbolNative: 'Rs', decimalDigits: 2, rounding: 0, flag: '🇲🇺' },
  { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'MVR', symbolNative: 'ރ.', decimalDigits: 2, rounding: 0, flag: '🇲🇻' },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MWK', symbolNative: 'MK', decimalDigits: 2, rounding: 0, flag: '🇲🇼' },
  { code: 'MXN', name: 'Mexican Peso', symbol: 'MX$', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇲🇽' },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'MYR', symbolNative: 'RM', decimalDigits: 2, rounding: 0, flag: '🇲🇾' },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MZN', symbolNative: 'MT', decimalDigits: 2, rounding: 0, flag: '🇲🇿' },
  { code: 'NAD', name: 'Namibian Dollar', symbol: 'NAD', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇳🇦' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: 'NGN', symbolNative: '₦', decimalDigits: 2, rounding: 0, flag: '🇳🇬' },
  { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'NIO', symbolNative: 'C$', decimalDigits: 2, rounding: 0, flag: '🇳🇮' },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'NOK', symbolNative: 'kr', decimalDigits: 2, rounding: 0, flag: '🇳🇴' },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: 'NPR', symbolNative: 'Rs', decimalDigits: 2, rounding: 0, flag: '🇳🇵' },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇳🇿' },
  { code: 'OMR', name: 'Omani Rial', symbol: 'OMR', symbolNative: 'ر.ع.', decimalDigits: 3, rounding: 0, flag: '🇴🇲' },
  { code: 'PAB', name: 'Panamanian Balboa', symbol: 'PAB', symbolNative: 'B/.', decimalDigits: 2, rounding: 0, flag: '🇵🇦' },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'PEN', symbolNative: 'S/', decimalDigits: 2, rounding: 0, flag: '🇵🇪' },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'PGK', symbolNative: 'K', decimalDigits: 2, rounding: 0, flag: '🇵🇬' },
  { code: 'PHP', name: 'Philippine Peso', symbol: 'PHP', symbolNative: '₱', decimalDigits: 2, rounding: 0, flag: '🇵🇭' },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: 'PKR', symbolNative: 'Rs', decimalDigits: 2, rounding: 0, flag: '🇵🇰' },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'PLN', symbolNative: 'zł', decimalDigits: 2, rounding: 0, flag: '🇵🇱' },
  { code: 'PYG', name: 'Paraguayan Guarani', symbol: 'PYG', symbolNative: '₲', decimalDigits: 0, rounding: 0, flag: '🇵🇾' },
  { code: 'QAR', name: 'Qatari Rial', symbol: 'QAR', symbolNative: 'ر.ق', decimalDigits: 2, rounding: 0, flag: '🇶🇦' },
  { code: 'RON', name: 'Romanian Leu', symbol: 'RON', symbolNative: 'lei', decimalDigits: 2, rounding: 0, flag: '🇷🇴' },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'RSD', symbolNative: 'дин', decimalDigits: 2, rounding: 0, flag: '🇷🇸' },
  { code: 'RUB', name: 'Russian Ruble', symbol: 'RUB', symbolNative: '₽', decimalDigits: 2, rounding: 0, flag: '🇷🇺' },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'RWF', symbolNative: 'FRw', decimalDigits: 0, rounding: 0, flag: '🇷🇼' },
  { code: 'SAR', name: 'Saudi Riyal', symbol: 'SAR', symbolNative: '﷼', decimalDigits: 2, rounding: 0, flag: '🇸🇦' },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: 'SBD', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇸🇧' },
  { code: 'SCR', name: 'Seychellois Rupee', symbol: 'SCR', symbolNative: 'Rs', decimalDigits: 2, rounding: 0, flag: '🇸🇨' },
  { code: 'SDG', name: 'Sudanese Pound', symbol: 'SDG', symbolNative: 'ج.س.', decimalDigits: 2, rounding: 0, flag: '🇸🇩' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'SEK', symbolNative: 'kr', decimalDigits: 2, rounding: 0, flag: '🇸🇪' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'SGD', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇸🇬' },
  { code: 'SHP', name: 'St. Helena Pound', symbol: 'SHP', symbolNative: '£', decimalDigits: 2, rounding: 0, flag: '🇸🇭' },
  { code: 'SLL', name: 'Sierra Leonean Leone', symbol: 'SLL', symbolNative: 'Le', decimalDigits: 0, rounding: 0, flag: '🇸🇱' },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'SOS', symbolNative: 'Sh', decimalDigits: 0, rounding: 0, flag: '🇸🇴' },
  { code: 'SRD', name: 'Surinamese Dollar', symbol: 'SRD', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇸🇷' },
  { code: 'SSP', name: 'South Sudanese Pound', symbol: 'SSP', symbolNative: '£', decimalDigits: 2, rounding: 0, flag: '🇸🇸' },
  { code: 'STN', name: 'São Tomé & Príncipe Dobra', symbol: 'STN', symbolNative: 'Db', decimalDigits: 2, rounding: 0, flag: '🇸🇹' },
  { code: 'SVC', name: 'Salvadoran Colón', symbol: 'SVC', symbolNative: '₡', decimalDigits: 2, rounding: 0, flag: '🇸🇻' },
  { code: 'SYP', name: 'Syrian Pound', symbol: 'SYP', symbolNative: '£', decimalDigits: 2, rounding: 0, flag: '🇸🇾' },
  { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'SZL', symbolNative: 'E', decimalDigits: 2, rounding: 0, flag: '🇸🇿' },
  { code: 'THB', name: 'Thai Baht', symbol: 'THB', symbolNative: '฿', decimalDigits: 2, rounding: 0, flag: '🇹🇭' },
  { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'TJS', symbolNative: 'ЅМ', decimalDigits: 2, rounding: 0, flag: '🇹🇯' },
  { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'TMT', symbolNative: 'm', decimalDigits: 2, rounding: 0, flag: '🇹🇲' },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'TND', symbolNative: 'د.ت', decimalDigits: 3, rounding: 0, flag: '🇹🇳' },
  { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'TOP', symbolNative: 'T$', decimalDigits: 2, rounding: 0, flag: '🇹🇴' },
  { code: 'TRY', name: 'Turkish Lira', symbol: 'TRY', symbolNative: '₺', decimalDigits: 2, rounding: 0, flag: '🇹🇷' },
  { code: 'TTD', name: 'Trinidad & Tobago Dollar', symbol: 'TTD', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇹🇹' },
  { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇹🇼' },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TZS', symbolNative: 'Sh', decimalDigits: 2, rounding: 0, flag: '🇹🇿' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: 'UAH', symbolNative: '₴', decimalDigits: 2, rounding: 0, flag: '🇺🇦' },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'UGX', symbolNative: 'USh', decimalDigits: 0, rounding: 0, flag: '🇺🇬' },
  { code: 'USD', name: 'US Dollar', symbol: '$', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇺🇸' },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: 'UYU', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇺🇾' },
  { code: 'UZS', name: 'Uzbekistani Som', symbol: 'UZS', symbolNative: 'сўм', decimalDigits: 2, rounding: 0, flag: '🇺🇿' },
  { code: 'VES', name: 'Venezuelan Bolívar', symbol: 'VES', symbolNative: 'Bs', decimalDigits: 2, rounding: 0, flag: '🇻🇪' },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', symbolNative: '₫', decimalDigits: 0, rounding: 0, flag: '🇻🇳' },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VUV', symbolNative: 'VT', decimalDigits: 0, rounding: 0, flag: '🇻🇺' },
  { code: 'WST', name: 'Samoan Tala', symbol: 'WST', symbolNative: 'T', decimalDigits: 2, rounding: 0, flag: '🇼🇸' },
  { code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA', symbolNative: 'FCFA', decimalDigits: 0, rounding: 0, flag: '🌍' },
  { code: 'XCD', name: 'East Caribbean Dollar', symbol: 'EC$', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🏝️' },
  { code: 'XOF', name: 'West African CFA Franc', symbol: 'F CFA', symbolNative: 'FCFA', decimalDigits: 0, rounding: 0, flag: '🌍' },
  { code: 'XPF', name: 'CFP Franc', symbol: 'FCFP', symbolNative: '₣', decimalDigits: 0, rounding: 0, flag: '🇵🇫' },
  { code: 'YER', name: 'Yemeni Rial', symbol: 'YER', symbolNative: '﷼', decimalDigits: 2, rounding: 0, flag: '🇾🇪' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'ZAR', symbolNative: 'R', decimalDigits: 2, rounding: 0, flag: '🇿🇦' },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZMW', symbolNative: 'ZK', decimalDigits: 2, rounding: 0, flag: '🇿🇲' },
  { code: 'ZWL', name: 'Zimbabwean Dollar', symbol: 'ZWL', symbolNative: '$', decimalDigits: 2, rounding: 0, flag: '🇿🇼' },
]

export function getCurrencyInfo(code: string): CurrencyInfo {
  return ISO_CURRENCIES.find(c => c.code === code) || ISO_CURRENCIES.find(c => c.code === 'USD')!
}

export function isZeroDecimalCurrency(code: string): boolean {
  return getCurrencyInfo(code).decimalDigits === 0
}
